using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace City3DDesktop.Services;

/// <summary>
/// 智能3D模型生成服务 - 整合识别、爬虫、生成的完整流程
/// </summary>
public class IntelligentModelGenerationService
{
    private readonly VisionRecognitionService _visionService;
    private readonly WebCrawlerService _crawlerService;
    private readonly Dictionary<string, IGenerationStrategy> _strategies;

    public IntelligentModelGenerationService()
    {
        _visionService = new VisionRecognitionService();
        _crawlerService = new WebCrawlerService();

        // 注册各类别的生成策略
        _strategies = new Dictionary<string, IGenerationStrategy>
        {
            ["Vehicle"] = new VehicleGenerationStrategy(),
            ["Building"] = new BuildingGenerationStrategy(),
            ["Character"] = new CharacterGenerationStrategy(),
            ["Product"] = new ProductGenerationStrategy(),
            ["Animal"] = new AnimalGenerationStrategy(),
            ["Furniture"] = new FurnitureGenerationStrategy(),
            ["Other"] = new GenericGenerationStrategy()
        };
    }

    /// <summary>
    /// 完整的智能生成流程
    /// </summary>
    public async Task<string> GenerateFromImageAsync(
        string imagePath,
        GenerationConfig config,
        Action<string, int> onProgress = null)
    {
        try
        {
            // 阶段1：图片识别 (0-15%)
            onProgress?.Invoke("正在识别图片内容...", 0);
            var recognition = await _visionService.RecognizeAsync(
                imagePath,
                config.VisionProvider,
                config.VisionApiKey
            );
            onProgress?.Invoke($"识别完成: {recognition.Name} ({recognition.Category})", 15);

            // 阶段2：收集元数据 (15-50%)
            onProgress?.Invoke("正在收集网络数据...", 15);
            var metadata = await _crawlerService.CollectMetadataAsync(
                recognition,
                (msg, percent) => onProgress?.Invoke(msg, 15 + (int)(percent * 0.35))
            );
            onProgress?.Invoke("数据收集完成", 50);

            // 阶段3：选择生成策略 (50-55%)
            onProgress?.Invoke("正在选择生成策略...", 50);
            var strategy = SelectStrategy(recognition.Category);
            onProgress?.Invoke($"使用策略: {strategy.GetType().Name}", 55);

            // 阶段4：生成基础形状 (55-70%)
            onProgress?.Invoke("正在生成基础形状...", 55);
            var baseMesh = await strategy.GenerateBaseShapeAsync(
                metadata,
                config,
                (msg, percent) => onProgress?.Invoke(msg, 55 + (int)(percent * 0.15))
            );
            onProgress?.Invoke("基础形状生成完成", 70);

            // 阶段5：细节雕刻 (70-85%)
            onProgress?.Invoke("正在雕刻细节...", 70);
            var detailedMesh = await strategy.SculptDetailsAsync(
                baseMesh,
                imagePath,
                metadata,
                config,
                (msg, percent) => onProgress?.Invoke(msg, 70 + (int)(percent * 0.15))
            );
            onProgress?.Invoke("细节雕刻完成", 85);

            // 阶段6：纹理映射 (85-95%)
            onProgress?.Invoke("正在应用纹理...", 85);
            var texturedMesh = await strategy.ApplyTextureAsync(
                detailedMesh,
                imagePath,
                metadata,
                config,
                (msg, percent) => onProgress?.Invoke(msg, 85 + (int)(percent * 0.10))
            );
            onProgress?.Invoke("纹理应用完成", 95);

            // 阶段7：导出模型 (95-100%)
            onProgress?.Invoke("正在导出模型...", 95);
            var outputPath = await ExportModelAsync(texturedMesh, config);
            onProgress?.Invoke("模型生成完成！", 100);

            return outputPath;
        }
        catch (Exception ex)
        {
            onProgress?.Invoke($"生成失败: {ex.Message}", -1);
            throw;
        }
    }

    /// <summary>
    /// 选择生成策略
    /// </summary>
    private IGenerationStrategy SelectStrategy(string category)
    {
        return _strategies.ContainsKey(category)
            ? _strategies[category]
            : _strategies["Other"];
    }

    /// <summary>
    /// 导出模型
    /// </summary>
    private async Task<string> ExportModelAsync(Mesh mesh, GenerationConfig config)
    {
        var outputDir = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
            "City3D",
            "Generated"
        );
        Directory.CreateDirectory(outputDir);

        var timestamp = DateTime.Now.ToString("yyyyMMdd_HHmmss");
        var outputPath = Path.Combine(outputDir, $"model_{timestamp}.obj");

        await Task.Run(() =>
        {
            using (var writer = new StreamWriter(outputPath))
            {
                // 写入OBJ文件头
                writer.WriteLine("# Generated by City3D Intelligent Model Generator");
                writer.WriteLine($"# Date: {DateTime.Now}");
                writer.WriteLine();

                // 写入顶点
                foreach (var vertex in mesh.Vertices)
                {
                    writer.WriteLine($"v {vertex.X:F6} {vertex.Y:F6} {vertex.Z:F6}");
                }
                writer.WriteLine();

                // 写入法线
                foreach (var normal in mesh.Normals)
                {
                    writer.WriteLine($"vn {normal.X:F6} {normal.Y:F6} {normal.Z:F6}");
                }
                writer.WriteLine();

                // 写入UV坐标
                foreach (var uv in mesh.UVs)
                {
                    writer.WriteLine($"vt {uv.X:F6} {uv.Y:F6}");
                }
                writer.WriteLine();

                // 写入面
                foreach (var face in mesh.Faces)
                {
                    writer.WriteLine($"f {face.V1 + 1}/{face.V1 + 1}/{face.V1 + 1} " +
                                   $"{face.V2 + 1}/{face.V2 + 1}/{face.V2 + 1} " +
                                   $"{face.V3 + 1}/{face.V3 + 1}/{face.V3 + 1}");
                }
            }
        });

        return outputPath;
    }
}

/// <summary>
/// 生成配置
/// </summary>
public class GenerationConfig
{
    // 识别配置
    public VisionRecognitionService.Provider VisionProvider { get; set; } = VisionRecognitionService.Provider.Doubao;
    public string VisionApiKey { get; set; }

    // 质量配置
    public QualityLevel Quality { get; set; } = QualityLevel.Industrial;
    public int Resolution { get; set; } = 512; // 基础分辨率
    public int SubdivisionLevel { get; set; } = 3; // 细分级别（工业级）

    // 细节配置
    public bool EnableDetailSculpting { get; set; } = true;
    public bool EnableTextureMapping { get; set; } = true;
    public bool EnableNormalMapping { get; set; } = true;
    public bool EnablePBRMaterials { get; set; } = true;

    // 性能配置
    public int MaxGenerationTimeMinutes { get; set; } = 60; // 最大生成时间
    public bool UseMultiThreading { get; set; } = true;
}

public enum QualityLevel
{
    Draft,      // 草图级（快速预览）
    Standard,   // 标准级（一般用途）
    High,       // 高质量（专业用途）
    Industrial  // 工业级（最高质量）
}

/// <summary>
/// 生成策略接口
/// </summary>
public interface IGenerationStrategy
{
    Task<Mesh> GenerateBaseShapeAsync(
        ObjectMetadata metadata,
        GenerationConfig config,
        Action<string, int> onProgress);

    Task<Mesh> SculptDetailsAsync(
        Mesh baseMesh,
        string imagePath,
        ObjectMetadata metadata,
        GenerationConfig config,
        Action<string, int> onProgress);

    Task<Mesh> ApplyTextureAsync(
        Mesh mesh,
        string imagePath,
        ObjectMetadata metadata,
        GenerationConfig config,
        Action<string, int> onProgress);
}

/// <summary>
/// 网格数据结构
/// </summary>
public class Mesh
{
    public List<Vector3> Vertices { get; set; } = new();
    public List<Vector3> Normals { get; set; } = new();
    public List<Vector2> UVs { get; set; } = new();
    public List<Face> Faces { get; set; } = new();
    public Dictionary<string, object> Metadata { get; set; } = new();
}

public struct Vector3
{
    public double X, Y, Z;

    public Vector3(double x, double y, double z)
    {
        X = x; Y = y; Z = z;
    }

    public static Vector3 operator +(Vector3 a, Vector3 b) => new(a.X + b.X, a.Y + b.Y, a.Z + b.Z);
    public static Vector3 operator -(Vector3 a, Vector3 b) => new(a.X - b.X, a.Y - b.Y, a.Z - b.Z);
    public static Vector3 operator *(Vector3 a, double s) => new(a.X * s, a.Y * s, a.Z * s);
    public static Vector3 operator /(Vector3 a, double s) => new(a.X / s, a.Y / s, a.Z / s);

    public double Length() => Math.Sqrt(X * X + Y * Y + Z * Z);
    public Vector3 Normalized() => this / Length();

    public static Vector3 Cross(Vector3 a, Vector3 b) => new(
        a.Y * b.Z - a.Z * b.Y,
        a.Z * b.X - a.X * b.Z,
        a.X * b.Y - a.Y * b.X
    );

    public static double Dot(Vector3 a, Vector3 b) => a.X * b.X + a.Y * b.Y + a.Z * b.Z;
}

public struct Vector2
{
    public double X, Y;

    public Vector2(double x, double y)
    {
        X = x; Y = y;
    }
}

public struct Face
{
    public int V1, V2, V3;

    public Face(int v1, int v2, int v3)
    {
        V1 = v1; V2 = v2; V3 = v3;
    }
}
